# bitcoind
BTC_RPC_USER = "user"
BTC_RPC_PASSWD = "passwd"
BTC_RPC_HOST = "localhost"
BTC_RPC_PORT = 18443
BTC_NETWORK = "regtest"

# CHAIN MONITOR
POLLING_DELTA = 60
BLOCK_WINDOW_SIZE = 10

# ZMQ
FEED_PROTOCOL = "tcp"
FEED_ADDR = "127.0.0.1"
FEED_PORT = 28332

# PISA
MAX_APPOINTMENTS = 100
EXPIRY_DELTA = 6
MIN_TO_SELF_DELAY = 20
SERVER_LOG_FILE = "pisa.log"
PISA_SECRET_KEY = "pisa_sk.der"

# PISA-CLI
CLIENT_LOG_FILE = "pisa.log"

# TEST
TEST_LOG_FILE = "test.log"

# LEVELDB
DB_PATH = "appointments"
