# bitcoind
BTC_RPC_USER = None
BTC_RPC_PASSWD = None
BTC_RPC_HOST = None
BTC_RPC_PORT = None
BTC_NETWORK = None


# ZMQ
FEED_PROTOCOL = None
FEED_ADDR = None
FEED_PORT = None

# PISA
MAX_APPOINTMENTS = 100
EXPIRY_DELTA = 6
MIN_DISPUTE_DELTA = 20
SERVER_LOG_FILE = 'pisa.log'
DB_PATH = 'appointments/'
SIGNING_KEY_DER = None

# PISA-CLI
CLIENT_LOG_FILE = 'pisa.log'

# CRYPTO
SUPPORTED_HASH_FUNCTIONS = ["SHA256"]
SUPPORTED_CIPHERS = ["AES-GCM-128"]
