# bitcoind
BTC_RPC_USER = None
BTC_RPC_PASSWD = None
BTC_RPC_HOST = None
BTC_RPC_PORT = None
BTC_NETWORK = None

# ZMQ
FEED_PROTOCOL = None
FEED_ADDR = None
FEED_PORT = None

# PISA
MAX_APPOINTMENTS = 100
EXPIRY_DELTA = 6
MIN_DISPUTE_DELTA = 20
SERVER_LOG_FILE = 'pisa.log'
PISA_SECRET_KEY = 'pisa_sk.pem'

# PISA-CLI
CLIENT_LOG_FILE = 'pisa.log'

# TEST
TEST_LOG_FILE = "test.log"

# CRYPTO
SUPPORTED_HASH_FUNCTIONS = ["SHA256"]
SUPPORTED_CIPHERS = ["AES-GCM-128"]

# LEVELDB
DB_PATH = "appointments"
WATCHER_PREFIX = "w"
WATCHER_LAST_BLOCK_KEY = "bw"
RESPONDER_PREFIX = "r"
RESPONDER_LAST_BLOCK_KEY = "br"
LOCATOR_MAP_PREFIX = 'm'
