def show_usage():
    return (
        "USAGE: "
        "\n\tteosd [global options]"
        "\n\nGLOBAL OPTIONS (all modifiable in conf file):"
        "\n\t--apibind \t\tAddress that teos API will bind to. Defaults to 'localhost'."
        "\n\t--apiport \t\tPort that teos API will bind to. Defaults to '9814'."
        "\n\t--rpcbind \t\tAddress that teos RPC server will bind to. Defaults to 'localhost'."
        "\n\t--rpcport \t\tPort that teos RPC server will bind to. Defaults to '8814'."
        "\n\t--btcnetwork \t\tNetwork bitcoind is connected to. Either mainnet, testnet or regtest. Defaults to "
        "'mainnet'."
        "\n\t--btcrpcuser \t\tbitcoind rpcuser. Defaults to 'user'."
        "\n\t--btcrpcpassword \tbitcoind rpcpassword. Defaults to 'passwd'."
        "\n\t--btcrpcconnect \tbitcoind rpcconnect. Defaults to 'localhost'."
        "\n\t--btcrpcport \t\tbitcoind rpcport. Defaults to '8332'."
        "\n\t--btcfeedconnect \tbitcoind zmq hostname (for blocks). Defaults to 'localhost'."
        "\n\t--btcfeedport \t\tbitcoind zmq port (for blocks). Defaults to '28332'."
        "\n\t--datadir \t\tSpecify data directory. Defaults to '~\\.teos'."
        "\n\t--wsgi \t\t\tThe WSGI server used to run the API. Either 'gunicorn' or 'waitress'. Defaults to 'gunicorn'."
        "\n\t       \t\t\tNotice 'gunicorn' does not work on Windows, so Windows users must use 'waitress'."
        "\n\t-d, --daemon \t\tRun in background as a daemon."
        "\n\t--overwritekey \t\tOverwrites the tower secret key. THIS IS IRREVERSIBLE AND WILL CHANGE YOUR TOWER ID."
        "\n\t-h, --help \t\tShows this message."
    )
