# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import teos.protobuf.appointment_pb2 as appointment__pb2
import teos.protobuf.user_pb2 as user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="api.proto",
    package="teos",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\tapi.proto\x12\x04teos\x1a\x11\x61ppointment.proto\x1a\nuser.proto2\xd3\x01\n\x03\x41PI\x12,\n\x08register\x12\n.teos.User\x1a\x12.teos.Subscription"\x00\x12N\n\x0f\x61\x64\x64_appointment\x12\x1b.teos.AddAppointmentRequest\x1a\x1c.teos.AddAppointmentResponse"\x00\x12N\n\x0fget_appointment\x12\x1b.teos.GetAppointmentRequest\x1a\x1c.teos.GetAppointmentResponse"\x00\x62\x06proto3',
    dependencies=[appointment__pb2.DESCRIPTOR, user__pb2.DESCRIPTOR],
)


_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_API = _descriptor.ServiceDescriptor(
    name="API",
    full_name="teos.API",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=51,
    serialized_end=262,
    methods=[
        _descriptor.MethodDescriptor(
            name="register",
            full_name="teos.API.register",
            index=0,
            containing_service=None,
            input_type=user__pb2._USER,
            output_type=user__pb2._SUBSCRIPTION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="add_appointment",
            full_name="teos.API.add_appointment",
            index=1,
            containing_service=None,
            input_type=appointment__pb2._ADDAPPOINTMENTREQUEST,
            output_type=appointment__pb2._ADDAPPOINTMENTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_appointment",
            full_name="teos.API.get_appointment",
            index=2,
            containing_service=None,
            input_type=appointment__pb2._GETAPPOINTMENTREQUEST,
            output_type=appointment__pb2._GETAPPOINTMENTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_API)

DESCRIPTOR.services_by_name["API"] = _API

# @@protoc_insertion_point(module_scope)
