# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appointment.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="appointment.proto",
    package="teos.protobuf.protos.v1",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x11\x61ppointment.proto\x12\x17teos.protobuf.protos.v1\x1a\x1cgoogle/protobuf/struct.proto"M\n\x0b\x41ppointment\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x16\n\x0e\x65ncrypted_blob\x18\x02 \x01(\t\x12\x15\n\rto_self_delay\x18\x03 \x01(\r"]\n\x07Tracker\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x14\n\x0c\x64ispute_txid\x18\x02 \x01(\t\x12\x14\n\x0cpenalty_txid\x18\x03 \x01(\t\x12\x15\n\rpenalty_rawtx\x18\x04 \x01(\t"\x97\x01\n\x0f\x41ppointmentData\x12;\n\x0b\x61ppointment\x18\x01 \x01(\x0b\x32$.teos.protobuf.protos.v1.AppointmentH\x00\x12\x33\n\x07tracker\x18\x02 \x01(\x0b\x32 .teos.protobuf.protos.v1.TrackerH\x00\x42\x12\n\x10\x61ppointment_data"e\n\x15\x41\x64\x64\x41ppointmentRequest\x12\x39\n\x0b\x61ppointment\x18\x01 \x01(\x0b\x32$.teos.protobuf.protos.v1.Appointment\x12\x11\n\tsignature\x18\x02 \x01(\t"\x87\x01\n\x16\x41\x64\x64\x41ppointmentResponse\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x13\n\x0bstart_block\x18\x02 \x01(\r\x12\x11\n\tsignature\x18\x03 \x01(\t\x12\x17\n\x0f\x61vailable_slots\x18\x04 \x01(\r\x12\x1b\n\x13subscription_expiry\x18\x05 \x01(\r";\n\x15GetAppointmentRequest\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\t"l\n\x16GetAppointmentResponse\x12\x42\n\x10\x61ppointment_data\x18\x01 \x01(\x0b\x32(.teos.protobuf.protos.v1.AppointmentData\x12\x0e\n\x06status\x18\x02 \x01(\t"K\n\x1aGetAllAppointmentsResponse\x12-\n\x0c\x61ppointments\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Structb\x06proto3',
    dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR],
)


_APPOINTMENT = _descriptor.Descriptor(
    name="Appointment",
    full_name="teos.protobuf.protos.v1.Appointment",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="locator",
            full_name="teos.protobuf.protos.v1.Appointment.locator",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="encrypted_blob",
            full_name="teos.protobuf.protos.v1.Appointment.encrypted_blob",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="to_self_delay",
            full_name="teos.protobuf.protos.v1.Appointment.to_self_delay",
            index=2,
            number=3,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=76,
    serialized_end=153,
)


_TRACKER = _descriptor.Descriptor(
    name="Tracker",
    full_name="teos.protobuf.protos.v1.Tracker",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="locator",
            full_name="teos.protobuf.protos.v1.Tracker.locator",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="dispute_txid",
            full_name="teos.protobuf.protos.v1.Tracker.dispute_txid",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="penalty_txid",
            full_name="teos.protobuf.protos.v1.Tracker.penalty_txid",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="penalty_rawtx",
            full_name="teos.protobuf.protos.v1.Tracker.penalty_rawtx",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=155,
    serialized_end=248,
)


_APPOINTMENTDATA = _descriptor.Descriptor(
    name="AppointmentData",
    full_name="teos.protobuf.protos.v1.AppointmentData",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="appointment",
            full_name="teos.protobuf.protos.v1.AppointmentData.appointment",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="tracker",
            full_name="teos.protobuf.protos.v1.AppointmentData.tracker",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="appointment_data",
            full_name="teos.protobuf.protos.v1.AppointmentData.appointment_data",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        )
    ],
    serialized_start=251,
    serialized_end=402,
)


_ADDAPPOINTMENTREQUEST = _descriptor.Descriptor(
    name="AddAppointmentRequest",
    full_name="teos.protobuf.protos.v1.AddAppointmentRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="appointment",
            full_name="teos.protobuf.protos.v1.AddAppointmentRequest.appointment",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="signature",
            full_name="teos.protobuf.protos.v1.AddAppointmentRequest.signature",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=404,
    serialized_end=505,
)


_ADDAPPOINTMENTRESPONSE = _descriptor.Descriptor(
    name="AddAppointmentResponse",
    full_name="teos.protobuf.protos.v1.AddAppointmentResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="locator",
            full_name="teos.protobuf.protos.v1.AddAppointmentResponse.locator",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="start_block",
            full_name="teos.protobuf.protos.v1.AddAppointmentResponse.start_block",
            index=1,
            number=2,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="signature",
            full_name="teos.protobuf.protos.v1.AddAppointmentResponse.signature",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="available_slots",
            full_name="teos.protobuf.protos.v1.AddAppointmentResponse.available_slots",
            index=3,
            number=4,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="subscription_expiry",
            full_name="teos.protobuf.protos.v1.AddAppointmentResponse.subscription_expiry",
            index=4,
            number=5,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=508,
    serialized_end=643,
)


_GETAPPOINTMENTREQUEST = _descriptor.Descriptor(
    name="GetAppointmentRequest",
    full_name="teos.protobuf.protos.v1.GetAppointmentRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="locator",
            full_name="teos.protobuf.protos.v1.GetAppointmentRequest.locator",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="signature",
            full_name="teos.protobuf.protos.v1.GetAppointmentRequest.signature",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=645,
    serialized_end=704,
)


_GETAPPOINTMENTRESPONSE = _descriptor.Descriptor(
    name="GetAppointmentResponse",
    full_name="teos.protobuf.protos.v1.GetAppointmentResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="appointment_data",
            full_name="teos.protobuf.protos.v1.GetAppointmentResponse.appointment_data",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="status",
            full_name="teos.protobuf.protos.v1.GetAppointmentResponse.status",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=706,
    serialized_end=814,
)


_GETALLAPPOINTMENTSRESPONSE = _descriptor.Descriptor(
    name="GetAllAppointmentsResponse",
    full_name="teos.protobuf.protos.v1.GetAllAppointmentsResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="appointments",
            full_name="teos.protobuf.protos.v1.GetAllAppointmentsResponse.appointments",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=816,
    serialized_end=891,
)

_APPOINTMENTDATA.fields_by_name["appointment"].message_type = _APPOINTMENT
_APPOINTMENTDATA.fields_by_name["tracker"].message_type = _TRACKER
_APPOINTMENTDATA.oneofs_by_name["appointment_data"].fields.append(_APPOINTMENTDATA.fields_by_name["appointment"])
_APPOINTMENTDATA.fields_by_name["appointment"].containing_oneof = _APPOINTMENTDATA.oneofs_by_name["appointment_data"]
_APPOINTMENTDATA.oneofs_by_name["appointment_data"].fields.append(_APPOINTMENTDATA.fields_by_name["tracker"])
_APPOINTMENTDATA.fields_by_name["tracker"].containing_oneof = _APPOINTMENTDATA.oneofs_by_name["appointment_data"]
_ADDAPPOINTMENTREQUEST.fields_by_name["appointment"].message_type = _APPOINTMENT
_GETAPPOINTMENTRESPONSE.fields_by_name["appointment_data"].message_type = _APPOINTMENTDATA
_GETALLAPPOINTMENTSRESPONSE.fields_by_name["appointments"].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name["Appointment"] = _APPOINTMENT
DESCRIPTOR.message_types_by_name["Tracker"] = _TRACKER
DESCRIPTOR.message_types_by_name["AppointmentData"] = _APPOINTMENTDATA
DESCRIPTOR.message_types_by_name["AddAppointmentRequest"] = _ADDAPPOINTMENTREQUEST
DESCRIPTOR.message_types_by_name["AddAppointmentResponse"] = _ADDAPPOINTMENTRESPONSE
DESCRIPTOR.message_types_by_name["GetAppointmentRequest"] = _GETAPPOINTMENTREQUEST
DESCRIPTOR.message_types_by_name["GetAppointmentResponse"] = _GETAPPOINTMENTRESPONSE
DESCRIPTOR.message_types_by_name["GetAllAppointmentsResponse"] = _GETALLAPPOINTMENTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Appointment = _reflection.GeneratedProtocolMessageType(
    "Appointment",
    (_message.Message,),
    {
        "DESCRIPTOR": _APPOINTMENT,
        "__module__": "appointment_pb2"
        # @@protoc_insertion_point(class_scope:teos.protobuf.protos.v1.Appointment)
    },
)
_sym_db.RegisterMessage(Appointment)

Tracker = _reflection.GeneratedProtocolMessageType(
    "Tracker",
    (_message.Message,),
    {
        "DESCRIPTOR": _TRACKER,
        "__module__": "appointment_pb2"
        # @@protoc_insertion_point(class_scope:teos.protobuf.protos.v1.Tracker)
    },
)
_sym_db.RegisterMessage(Tracker)

AppointmentData = _reflection.GeneratedProtocolMessageType(
    "AppointmentData",
    (_message.Message,),
    {
        "DESCRIPTOR": _APPOINTMENTDATA,
        "__module__": "appointment_pb2"
        # @@protoc_insertion_point(class_scope:teos.protobuf.protos.v1.AppointmentData)
    },
)
_sym_db.RegisterMessage(AppointmentData)

AddAppointmentRequest = _reflection.GeneratedProtocolMessageType(
    "AddAppointmentRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _ADDAPPOINTMENTREQUEST,
        "__module__": "appointment_pb2"
        # @@protoc_insertion_point(class_scope:teos.protobuf.protos.v1.AddAppointmentRequest)
    },
)
_sym_db.RegisterMessage(AddAppointmentRequest)

AddAppointmentResponse = _reflection.GeneratedProtocolMessageType(
    "AddAppointmentResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _ADDAPPOINTMENTRESPONSE,
        "__module__": "appointment_pb2"
        # @@protoc_insertion_point(class_scope:teos.protobuf.protos.v1.AddAppointmentResponse)
    },
)
_sym_db.RegisterMessage(AddAppointmentResponse)

GetAppointmentRequest = _reflection.GeneratedProtocolMessageType(
    "GetAppointmentRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETAPPOINTMENTREQUEST,
        "__module__": "appointment_pb2"
        # @@protoc_insertion_point(class_scope:teos.protobuf.protos.v1.GetAppointmentRequest)
    },
)
_sym_db.RegisterMessage(GetAppointmentRequest)

GetAppointmentResponse = _reflection.GeneratedProtocolMessageType(
    "GetAppointmentResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETAPPOINTMENTRESPONSE,
        "__module__": "appointment_pb2"
        # @@protoc_insertion_point(class_scope:teos.protobuf.protos.v1.GetAppointmentResponse)
    },
)
_sym_db.RegisterMessage(GetAppointmentResponse)

GetAllAppointmentsResponse = _reflection.GeneratedProtocolMessageType(
    "GetAllAppointmentsResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETALLAPPOINTMENTSRESPONSE,
        "__module__": "appointment_pb2"
        # @@protoc_insertion_point(class_scope:teos.protobuf.protos.v1.GetAllAppointmentsResponse)
    },
)
_sym_db.RegisterMessage(GetAllAppointmentsResponse)


# @@protoc_insertion_point(module_scope)
