# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import teos.protobuf.appointment_pb2 as appointment__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class RPC_APIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_all_appointments = channel.unary_unary(
            "/teos.RPC_API/get_all_appointments",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=appointment__pb2.GetAllAppointmentsResponse.FromString,
        )


class RPC_APIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_all_appointments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RPC_APIServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "get_all_appointments": grpc.unary_unary_rpc_method_handler(
            servicer.get_all_appointments,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=appointment__pb2.GetAllAppointmentsResponse.SerializeToString,
        )
    }
    generic_handler = grpc.method_handlers_generic_handler("teos.RPC_API", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class RPC_API(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_all_appointments(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/teos.RPC_API/get_all_appointments",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            appointment__pb2.GetAllAppointmentsResponse.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
