# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tower_services.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import teos.protobuf.appointment_pb2 as appointment__pb2
import teos.protobuf.user_pb2 as user__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="tower_services.proto",
    package="teos.protobuf.protos.v1",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x14tower_services.proto\x12\x17teos.protobuf.protos.v1\x1a\x11\x61ppointment.proto\x1a\nuser.proto\x1a\x1bgoogle/protobuf/empty.proto2\xcc\x06\n\rTowerServices\x12\x61\n\x08register\x12(.teos.protobuf.protos.v1.RegisterRequest\x1a).teos.protobuf.protos.v1.RegisterResponse"\x00\x12t\n\x0f\x61\x64\x64_appointment\x12..teos.protobuf.protos.v1.AddAppointmentRequest\x1a/.teos.protobuf.protos.v1.AddAppointmentResponse"\x00\x12t\n\x0fget_appointment\x12..teos.protobuf.protos.v1.GetAppointmentRequest\x1a/.teos.protobuf.protos.v1.GetAppointmentResponse"\x00\x12w\n\x10get_appointments\x12/.teos.protobuf.protos.v1.GetAppointmentsRequest\x1a\x30.teos.protobuf.protos.v1.GetAppointmentsResponse"\x00\x12\x65\n\x14get_all_appointments\x12\x16.google.protobuf.Empty\x1a\x33.teos.protobuf.protos.v1.GetAllAppointmentsResponse"\x00\x12Y\n\x0eget_tower_info\x12\x16.google.protobuf.Empty\x1a-.teos.protobuf.protos.v1.GetTowerInfoResponse"\x00\x12P\n\tget_users\x12\x16.google.protobuf.Empty\x1a).teos.protobuf.protos.v1.GetUsersResponse"\x00\x12_\n\x08get_user\x12\'.teos.protobuf.protos.v1.GetUserRequest\x1a(.teos.protobuf.protos.v1.GetUserResponse"\x00\x62\x06proto3',
    dependencies=[appointment__pb2.DESCRIPTOR, user__pb2.DESCRIPTOR, google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,],
)


_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_TOWERSERVICES = _descriptor.ServiceDescriptor(
    name="TowerServices",
    full_name="teos.protobuf.protos.v1.TowerServices",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=110,
    serialized_end=954,
    methods=[
        _descriptor.MethodDescriptor(
            name="register",
            full_name="teos.protobuf.protos.v1.TowerServices.register",
            index=0,
            containing_service=None,
            input_type=user__pb2._REGISTERREQUEST,
            output_type=user__pb2._REGISTERRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="add_appointment",
            full_name="teos.protobuf.protos.v1.TowerServices.add_appointment",
            index=1,
            containing_service=None,
            input_type=appointment__pb2._ADDAPPOINTMENTREQUEST,
            output_type=appointment__pb2._ADDAPPOINTMENTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_appointment",
            full_name="teos.protobuf.protos.v1.TowerServices.get_appointment",
            index=2,
            containing_service=None,
            input_type=appointment__pb2._GETAPPOINTMENTREQUEST,
            output_type=appointment__pb2._GETAPPOINTMENTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_appointments",
            full_name="teos.protobuf.protos.v1.TowerServices.get_appointments",
            index=3,
            containing_service=None,
            input_type=appointment__pb2._GETAPPOINTMENTSREQUEST,
            output_type=appointment__pb2._GETAPPOINTMENTSRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_all_appointments",
            full_name="teos.protobuf.protos.v1.TowerServices.get_all_appointments",
            index=4,
            containing_service=None,
            input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            output_type=appointment__pb2._GETALLAPPOINTMENTSRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_tower_info",
            full_name="teos.protobuf.protos.v1.TowerServices.get_tower_info",
            index=5,
            containing_service=None,
            input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            output_type=appointment__pb2._GETTOWERINFORESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_users",
            full_name="teos.protobuf.protos.v1.TowerServices.get_users",
            index=6,
            containing_service=None,
            input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            output_type=user__pb2._GETUSERSRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_user",
            full_name="teos.protobuf.protos.v1.TowerServices.get_user",
            index=7,
            containing_service=None,
            input_type=user__pb2._GETUSERREQUEST,
            output_type=user__pb2._GETUSERRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_TOWERSERVICES)

DESCRIPTOR.services_by_name["TowerServices"] = _TOWERSERVICES

# @@protoc_insertion_point(module_scope)
