# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tower_services.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import teos.protobuf.appointment_pb2 as appointment__pb2
import teos.protobuf.user_pb2 as user__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="tower_services.proto",
    package="teos.protobuf.protos.v1",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x14tower_services.proto\x12\x17teos.protobuf.protos.v1\x1a\x11\x61ppointment.proto\x1a\nuser.proto\x1a\x1bgoogle/protobuf/empty.proto"\x82\x01\n\x14GetTowerInfoResponse\x12\x1e\n\x16n_watcher_appointments\x18\x01 \x01(\r\x12\x1c\n\x14n_responder_trackers\x18\x02 \x01(\r\x12\x1a\n\x12n_registered_users\x18\x03 \x01(\r\x12\x10\n\x08tower_id\x18\x04 \x01(\t2\x8d\x06\n\rTowerServices\x12\x61\n\x08register\x12(.teos.protobuf.protos.v1.RegisterRequest\x1a).teos.protobuf.protos.v1.RegisterResponse"\x00\x12t\n\x0f\x61\x64\x64_appointment\x12..teos.protobuf.protos.v1.AddAppointmentRequest\x1a/.teos.protobuf.protos.v1.AddAppointmentResponse"\x00\x12t\n\x0fget_appointment\x12..teos.protobuf.protos.v1.GetAppointmentRequest\x1a/.teos.protobuf.protos.v1.GetAppointmentResponse"\x00\x12\x65\n\x14get_all_appointments\x12\x16.google.protobuf.Empty\x1a\x33.teos.protobuf.protos.v1.GetAllAppointmentsResponse"\x00\x12Y\n\x0eget_tower_info\x12\x16.google.protobuf.Empty\x1a-.teos.protobuf.protos.v1.GetTowerInfoResponse"\x00\x12P\n\tget_users\x12\x16.google.protobuf.Empty\x1a).teos.protobuf.protos.v1.GetUsersResponse"\x00\x12_\n\x08get_user\x12\'.teos.protobuf.protos.v1.GetUserRequest\x1a(.teos.protobuf.protos.v1.GetUserResponse"\x00\x12\x38\n\x04stop\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty"\x00\x62\x06proto3',
    dependencies=[appointment__pb2.DESCRIPTOR, user__pb2.DESCRIPTOR, google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,],
)


_GETTOWERINFORESPONSE = _descriptor.Descriptor(
    name="GetTowerInfoResponse",
    full_name="teos.protobuf.protos.v1.GetTowerInfoResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="n_watcher_appointments",
            full_name="teos.protobuf.protos.v1.GetTowerInfoResponse.n_watcher_appointments",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="n_responder_trackers",
            full_name="teos.protobuf.protos.v1.GetTowerInfoResponse.n_responder_trackers",
            index=1,
            number=2,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="n_registered_users",
            full_name="teos.protobuf.protos.v1.GetTowerInfoResponse.n_registered_users",
            index=2,
            number=3,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="tower_id",
            full_name="teos.protobuf.protos.v1.GetTowerInfoResponse.tower_id",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=110,
    serialized_end=240,
)

DESCRIPTOR.message_types_by_name["GetTowerInfoResponse"] = _GETTOWERINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetTowerInfoResponse = _reflection.GeneratedProtocolMessageType(
    "GetTowerInfoResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETTOWERINFORESPONSE,
        "__module__": "tower_services_pb2"
        # @@protoc_insertion_point(class_scope:teos.protobuf.protos.v1.GetTowerInfoResponse)
    },
)
_sym_db.RegisterMessage(GetTowerInfoResponse)


_TOWERSERVICES = _descriptor.ServiceDescriptor(
    name="TowerServices",
    full_name="teos.protobuf.protos.v1.TowerServices",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=243,
    serialized_end=1024,
    methods=[
        _descriptor.MethodDescriptor(
            name="register",
            full_name="teos.protobuf.protos.v1.TowerServices.register",
            index=0,
            containing_service=None,
            input_type=user__pb2._REGISTERREQUEST,
            output_type=user__pb2._REGISTERRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="add_appointment",
            full_name="teos.protobuf.protos.v1.TowerServices.add_appointment",
            index=1,
            containing_service=None,
            input_type=appointment__pb2._ADDAPPOINTMENTREQUEST,
            output_type=appointment__pb2._ADDAPPOINTMENTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_appointment",
            full_name="teos.protobuf.protos.v1.TowerServices.get_appointment",
            index=2,
            containing_service=None,
            input_type=appointment__pb2._GETAPPOINTMENTREQUEST,
            output_type=appointment__pb2._GETAPPOINTMENTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_all_appointments",
            full_name="teos.protobuf.protos.v1.TowerServices.get_all_appointments",
            index=3,
            containing_service=None,
            input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            output_type=appointment__pb2._GETALLAPPOINTMENTSRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_tower_info",
            full_name="teos.protobuf.protos.v1.TowerServices.get_tower_info",
            index=4,
            containing_service=None,
            input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            output_type=_GETTOWERINFORESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_users",
            full_name="teos.protobuf.protos.v1.TowerServices.get_users",
            index=5,
            containing_service=None,
            input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            output_type=user__pb2._GETUSERSRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_user",
            full_name="teos.protobuf.protos.v1.TowerServices.get_user",
            index=6,
            containing_service=None,
            input_type=user__pb2._GETUSERREQUEST,
            output_type=user__pb2._GETUSERRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="stop",
            full_name="teos.protobuf.protos.v1.TowerServices.stop",
            index=7,
            containing_service=None,
            input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_TOWERSERVICES)

DESCRIPTOR.services_by_name["TowerServices"] = _TOWERSERVICES

# @@protoc_insertion_point(module_scope)
